java_args: >
  -Xms32g
  -XX:+AlwaysPreTouch
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:HeapDumpPath=/var/log/jenkins/heap.dump
  -XX:+UseG1GC
  -XX:+UseStringDeduplication
  -XX:+ParallelRefProcEnabled
  -XX:+DisableExplicitGC
  -XX:+UnlockDiagnosticVMOptions
  -XX:+UnlockExperimentalVMOptions
  -verbose:gc
  -Xloggc:/var/log/jenkins/gc.log
  -XX:NumberOfGCLogFiles=5
  -XX:+UseGCLogFileRotation
  -XX:GCLogFileSize=100m
  -XX:+PrintGC
  -XX:+PrintGCDateStamps
  -XX:+PrintGCDetails
  -XX:+PrintHeapAtGC
  -XX:+PrintGCCause
  -XX:+PrintTenuringDistribution
  -XX:+PrintReferenceGC
  -XX:+PrintAdaptiveSizePolicy
  -XX:ErrorFile=/var/log/jenkins/hs_err_%p.log
  -XX:+LogVMOutput
  -XX:LogFile=/var/log/jenkins/jvm.log
  -Dmail.smtp.starttls.enable=true
  -Dhudson.slaves.WorkspaceList=..
  -Dcom.sun.management.jmxremote=true
  -Dcom.sun.management.jmxremote.port=9876
  -Dcom.sun.management.jmxremote.rmi.port=9876
  -Dcom.sun.management.jmxremote.local.only=false
  -Dcom.sun.management.jmxremote.ssl=false
  -Dcom.sun.management.jmxremote.authenticate=true
  -Dcom.sun.management.jmxremote.access.file=/var/lib/jenkins/.ssh/jmxremote.access
  -Dcom.sun.management.jmxremote.password.file=/var/lib/jenkins/.ssh/jmxremote.password
  -Djava.rmi.server.hostname={{ ansible_host }}

jenkins_home: /jenkins_home
